name: flutterdabao
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.7
  timeago: ^2.0.10
  percent_indicator: ^1.0.12
  smooth_star_rating: ^1.0.1
  datetime_picker_formfield: ^0.1.4
  flutter_colorpicker: any
  flutter_masked_text: ^0.6.0
  meta: ^1.1.6
  progress_hud: ^1.1.0
  flutter_spinkit: "^3.0.0"
  latlong: ^0.6.1
  cached_network_image: ^0.5.1
  progress_indicators: ^0.1.2
  image: ^2.0.5
  cloud_functions: ^0.0.5
  geolocator: '^2.1.1'
  google_maps_flutter: ^0.0.3+3 
  flutter_google_places: any
  shared_preferences: ^0.4.3
  material_search: ^0.2.8
  bubble_tab_indicator: "^0.1.4"
  url_launcher:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: ^0.19.0
  firebase_auth:
    git:
      url: git://github.com/cqhchan/plugins.git
      path: packages/firebase_auth
  firebase_messaging: ^2.1.0
  google_sign_in: ^3.2.2
  firebase: ^5.0.0
  flutter_typeahead: ^0.4.1
  cloud_firestore: ^0.8.2
  image_picker: 
  firebase_storage:
  random_string:
  firebase_dynamic_links: ^0.1.0+1
  path_provider: ^0.4.1
  date_format: ^1.0.5
  photo_view: ^0.1.2
  modal_progress_hud: ^0.1.2
  image_cropper: ^0.0.9
  geohash: ^0.2.1
  flutter_swiper: ^1.1.4
  path_drawing: ^0.4.0
  settings:
    git:
      url: https://github.com/cqhchan/settings

dev_dependencies:
  flutter_test:
    sdk: flutter

    


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/c

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

    #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF_UI_Display
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.otf
        - asset: assets/fonts/SF-UI-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-UI-Display-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF-UI-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-UI-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-UI-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-UI-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-UI-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-UI-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-UI-Display-Black.otf
          weight: 900

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
