name: flutterdabao
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  intl: ^0.15.7
  datetime_picker_formfield: ^0.1.4
  flutter_colorpicker: any
  flutter_masked_text: ^0.6.0
  meta: ^1.1.6
  card_settings: ^1.2.2
  progress_hud: ^1.1.0
  flutter_spinkit: "^3.0.0"
  google_maps_webservice: ^0.0.9
  latlong: ^0.6.1
  # time_slot_picker: ^0.0.1
  flutter:
    sdk: flutter
  image: ^2.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart:
    git:  git://github.com/ReactiveX/rxdart.git
  firebase_auth:
    git:
      url: git://github.com/cqhchan/plugins.git
      path: packages/firebase_auth


  # firebase_auth:
  #   path: ../../plugins/packages/firebase_auth

  google_sign_in: ^3.2.2
  firebase: ^5.0.0
  cloud_firestore: ^0.8.2
  image_picker: 
  firebase_storage:
  random_string:
  path_provider: ^0.4.1
  date_format: ^1.0.5
  modal_progress_hud: ^0.1.2
  image_cropper: ^0.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter

    


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/c

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

    #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF_UI_Display
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.otf
        - asset: assets/fonts/SF-UI-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-UI-Display-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF-UI-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-UI-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-UI-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-UI-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-UI-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-UI-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-UI-Display-Black.otf
          weight: 900

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
